[google_oauth_credentials]
type = "authorized_user"
client_id = "133420057519-mm4siqgcndsqc3a534a9s4jt5tuuppa2.apps.googleusercontent.com"
client_secret = "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"
refresh_token = ""
