OPENAI_API_KEY = "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"

[google_oauth_credentials]
type = "web"
client_id = "133420057519-0e4m36qeifv8cd4acvmct3adgse717er.apps.googleusercontent.com"
client_secret = "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"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
redirect_uri = "https://autoreport-pro.streamlit.app/oauth2callback"
