OPENAI_API_KEY = "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"  # Leave your GPT key unchanged

[google_oauth_credentials]
type = "installed"
client_id = "133420057519-fr0k81ofi9vpolcqfupe1qjthuamepao.apps.googleusercontent.com"
client_secret = "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"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
